# ZorkOS Termux Properties
# Made by Zork | 2026 Edition

extra-keys = [['ESC','/','-','HOME','UP','END','PGUP'],['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN']]
terminal-toolbar-show-extra-keys = true
terminal-margin-horizontal = 3
terminal-margin-vertical = 3
bell-character = vibrate
use-black-ui = true
